{
 "title": "Service metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Success/Error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_ms_count[5m]))\n",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(rate(http_request_errors_total[5m]))",
     "legendFormat": "Error"
    }
   ]
  },
  {
   "title": "Response time of /assess/",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (path) (increase(http_request_duration_ms_bucket{path=~\"/assess.*\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Usage ratio",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (top_path) (\n  label_replace(\n    increase(http_request_duration_ms_count[$__range]),\n    \"top_path\",\n    \"/$1\",\n    \"path\",\n    \"^/([^/]*).*\"\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}